### ISSUE TITLE
❌ Runtime error `gui` with `v1.10.0` release

### ISSUE THREAD

**Issue by DenisCarriere** [streamingfast/substreams#526]
- ❌ if I compile a new substreams with v1.10.0 and run `gui`, it throws an error
- ✅ if I use a previously compiled substreams v1.9.x and run `gui`, the new v1.10.0 works

```bash
substreams gui -e eos.substreams.pinax.network:443 ch_out -s 386946801 -t 386946802
Launching Substreams GUI...
Caught panic:

runtime error: invalid memory address or nil pointer dereference

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/debug/stack.go:16 +0x1c
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
        /Users/denis/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.6/tea.go:479 +0x88
panic({0x102e17320?, 0x1044ee1c0?})
        /opt/homebrew/Cellar/go/1.22.5/libexec/src/runtime/panic.go:770 +0x124
github.com/streamingfast/substreams/tui2/pages/request.(*Request).renderRequestSummary(0x140008d2190)
        /Users/denis/Github/substreams-cli/tui2/pages/request/request.go:159 +0x90
github.com/streamingfast/substreams/tui2/pages/request.(*Request).View(0x14000a02008?)
        /Users/denis/Github/substreams-cli/tui2/pages/request/request.go:148 +0x1c
github.com/streamingfast/substreams/tui2.(*UI).View(0x1400069bdd0)
        /Users/denis/Github/substreams-cli/tui2/ui.go:245 +0x330
github.com/charmbracelet/bubbletea.(*Program).Run(0x140008a1300)
        /Users/denis/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.26.6/tea.go:534 +0x6b8
main.runGui(0x104539480, {0x14000559c70?, 0x1?, 0x102234206?})
        /Users/denis/Github/substreams-cli/cmd/substreams/gui.go:147 +0x69c
github.com/spf13/cobra.(*Command).execute(0x104539480, {0x14000559b90, 0x7, 0x7})
        /Users/denis/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x10453c560)
        /Users/denis/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/denis/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /Users/denis/Github/substreams-cli/cmd/substreams/main.go:21 +0x7c
```

**Comment by sduchesneau** [comment]
The issue is that the syntax has changed: `substreams gui <moduleName>` is no longer supported.

You either run:
* `substreams gui` (no arg)
* `substreams gui <packageFile>` (no module Name, can be selected later in the GUI)
* `substreams gui <packageFile> <moduleName>`

Now, I'll fix the handling of this error for next release so that the error is clearer...
